---
- name: Uninstall wireshark from webservers, nfsservers
  hosts: webservers, nfs_servers
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: Uninstalling wireshark from webservers and nfsservers
      package:
        name: wireshark
        state: removed
        
- name: Uninstall wireshark from Loadbalancers and database servers
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Uninstalling wireshark from Loadbalancers and database servers
      package:
        name: wireshark-qt
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes