- hosts: lb
  roles:
    - { role: roles/nginx-lb, when: enable_nginx_lb and load_balancer_is_required }
    - { role: roles/apache-lb, when: enable_apache_lb and load_balancer_is_required }
  become: true 