# ---
# # - hosts: all
# # #- import_playbook: ../static-assignments/common.yml
# # - import_playbook: ../static-assignments/common-del.yml

# # - hosts: uat-webservers
# # - import_playbook: ../static-assignments/uat-webservers.yml
# ---
# #- hosts: all
# #- name: Include dynamic variables 
#  # tasks:
#   #import_playbook: ../static-assignments/common.yml 
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# #- hosts: webservers
# #- name: Webserver assignment
# # import_playbook: ../static-assignments/webservers.yml
# ---
# - hosts: db
# - name: install db
#   import_playbook: ../static-assignments/db.yml

---
- name: Include dynamic variables 
  hosts: lb

# - name: import common file
#   import_playbook: ../static-assignments/common.yml
#   tags:
#     - always

- name: include env-vars file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

# - hosts: db
# - name: import database file
#   import_playbook: ../static-assignments/db.yml

# - name: import webservers file
#   import_playbook: ../static-assignments/webservers.yml

- hosts: lb
- name: import Loadbalancers assignment
  
  import_playbook: ../static-assignments/lb.yml
  when: load_balancer_is_required